export interface PortfolioProject {
  id: string
  title: string
  category: 'Branding' | 'Social Media' | 'Print' | 'UI/UX' | 'Logo' | 'Marketing'
  image: string
  logo: string
  colors: string[]
  description: string
  industry: string
  slug: string
  heroImage: string
  fullDescription: string
  services: string[]
  timeline: string
  tools: string[]
  testimonial: {
    quote: string
    author: string
    role: string
    company: string
  }
  galleryImages: string[]
  socialMediaMockups: string[]
  printMockups: string[]
  uiMockups: string[]
  beforeAfter: {
    before: string
    after: string
  }
}

export const portfolioProjects: PortfolioProject[] = [
  {
    id: '1',
    title: 'LuxeVista Cosmetics',
    slug: 'luxevista',
    category: 'Branding',
    image: '/portfolio/luxevista.jpg',
    heroImage: '/portfolio/luxevista-hero.jpg',
    logo: '/portfolio/logos/luxevista-logo.png',
    colors: ['#FF6B9D', '#C44569', '#F8B500'],
    description: 'Complete brand identity redesign for luxury cosmetics brand including logo, packaging, and digital presence.',
    fullDescription: 'LuxeVista required a complete brand overhaul to position themselves as a premium luxury cosmetics brand in a competitive market. We created an elegant, sophisticated identity that resonates with their target demographic of affluent women aged 25-45.',
    industry: 'Beauty & Cosmetics',
    services: ['Logo Design', 'Brand Guidelines', 'Packaging Design', 'Digital Assets', 'Social Media Templates'],
    timeline: '4 months',
    tools: ['Adobe Creative Suite', 'Figma', 'Illustrator'],
    testimonial: {
      quote: 'NEXTPIXEL STUDIO transformed our brand into something truly luxurious and memorable. The level of detail and sophistication exceeded our expectations.',
      author: 'Isabella Romance',
      role: 'Founder & CEO',
      company: 'LuxeVista Cosmetics',
    },
    galleryImages: ['/portfolio/luxevista-gallery-1.jpg', '/portfolio/luxevista-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/luxevista-social-1.jpg', '/portfolio/luxevista-social-2.jpg', '/portfolio/luxevista-social-3.jpg'],
    printMockups: ['/portfolio/luxevista-print-1.jpg', '/portfolio/luxevista-print-2.jpg', '/portfolio/luxevista-print-3.jpg'],
    uiMockups: ['/portfolio/luxevista-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/luxevista-before.jpg',
      after: '/portfolio/luxevista-after.jpg',
    },
  },
  {
    id: '2',
    title: 'TechFlow Solutions',
    slug: 'techflow',
    category: 'UI/UX',
    image: '/portfolio/techflow.jpg',
    heroImage: '/portfolio/techflow-hero.jpg',
    logo: '/portfolio/logos/techflow-logo.png',
    colors: ['#3B6EB5', '#1F4D8F', '#5B8ED5'],
    description: 'Enterprise SaaS platform UI/UX design with modern interfaces and seamless user experience.',
    fullDescription: 'TechFlow Solutions needed a complete platform redesign to improve user engagement and reduce churn. We redesigned their entire interface with modern aesthetics, improved usability, and intuitive navigation for enterprise users.',
    industry: 'Technology',
    services: ['UI/UX Design', 'Wireframing', 'Prototyping', 'User Research', 'Design System'],
    timeline: '3 months',
    tools: ['Figma', 'Adobe XD', 'Framer'],
    testimonial: {
      quote: 'The new platform design has transformed how our users interact with our software. Adoption rates are up 45% since launch.',
      author: 'David Chen',
      role: 'VP Product',
      company: 'TechFlow Solutions',
    },
    galleryImages: ['/portfolio/techflow-gallery-1.jpg', '/portfolio/techflow-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/techflow-social-1.jpg', '/portfolio/techflow-social-2.jpg', '/portfolio/techflow-social-3.jpg'],
    printMockups: ['/portfolio/techflow-print-1.jpg', '/portfolio/techflow-print-2.jpg', '/portfolio/techflow-print-3.jpg'],
    uiMockups: ['/portfolio/techflow-ui-1.jpg', '/portfolio/techflow-ui-2.jpg', '/portfolio/techflow-ui-3.jpg'],
    beforeAfter: {
      before: '/portfolio/techflow-before.jpg',
      after: '/portfolio/techflow-after.jpg',
    },
  },
  {
    id: '3',
    title: 'Artisan Coffee Co',
    slug: 'artisan-coffee',
    category: 'Logo',
    image: '/portfolio/artisan.jpg',
    heroImage: '/portfolio/artisan-hero.jpg',
    logo: '/portfolio/logos/artisan-logo.png',
    colors: ['#8B4513', '#D2691E', '#FFE4B5'],
    description: 'Iconic logo and visual identity for premium specialty coffee roaster with heritage aesthetic.',
    fullDescription: 'Artisan Coffee Co required a distinctive logo that conveyed quality, heritage, and passion for coffee. We created an iconic mark that reflects their commitment to single-origin beans and traditional roasting methods.',
    industry: 'Food & Beverage',
    services: ['Logo Design', 'Packaging Design', 'Brand Guidelines', 'Label Design'],
    timeline: '6 weeks',
    tools: ['Illustrator', 'Adobe Creative Suite'],
    testimonial: {
      quote: 'Our new logo perfectly captures the essence of our craft. Customers have responded incredibly positively.',
      author: 'Marcus Thompson',
      role: 'Owner',
      company: 'Artisan Coffee Co',
    },
    galleryImages: ['/portfolio/artisan-gallery-1.jpg', '/portfolio/artisan-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/artisan-social-1.jpg', '/portfolio/artisan-social-2.jpg', '/portfolio/artisan-social-3.jpg'],
    printMockups: ['/portfolio/artisan-print-1.jpg', '/portfolio/artisan-print-2.jpg', '/portfolio/artisan-print-3.jpg'],
    uiMockups: ['/portfolio/artisan-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/artisan-before.jpg',
      after: '/portfolio/artisan-after.jpg',
    },
  },
  {
    id: '4',
    title: 'EcoGrow Sustainability',
    slug: 'ecogrow',
    category: 'Social Media',
    image: '/portfolio/ecogrow.jpg',
    heroImage: '/portfolio/ecogrow-hero.jpg',
    logo: '/portfolio/logos/ecogrow-logo.png',
    colors: ['#2D5F3F', '#4CAF50', '#81C784'],
    description: 'Comprehensive social media campaign for environmental sustainability initiative with engaging content.',
    fullDescription: 'EcoGrow needed a comprehensive social media strategy to raise awareness about sustainable living. We created compelling content that educated and inspired their audience while growing their community.',
    industry: 'Environmental',
    services: ['Social Media Strategy', 'Content Creation', 'Graphics Design', 'Campaign Management'],
    timeline: '3 months',
    tools: ['Adobe Creative Suite', 'Canva Pro'],
    testimonial: {
      quote: 'The social media campaign has been incredibly effective. We\'ve grown our followers by 300% and engagement is at record highs.',
      author: 'Sarah Williams',
      role: 'Marketing Director',
      company: 'EcoGrow Sustainability',
    },
    galleryImages: ['/portfolio/ecogrow-gallery-1.jpg', '/portfolio/ecogrow-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/ecogrow-social-1.jpg', '/portfolio/ecogrow-social-2.jpg', '/portfolio/ecogrow-social-3.jpg'],
    printMockups: ['/portfolio/ecogrow-print-1.jpg', '/portfolio/ecogrow-print-2.jpg', '/portfolio/ecogrow-print-3.jpg'],
    uiMockups: ['/portfolio/ecogrow-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/ecogrow-before.jpg',
      after: '/portfolio/ecogrow-after.jpg',
    },
  },
  {
    id: '5',
    title: 'Velocity Fitness',
    slug: 'velocity-fitness',
    category: 'Marketing',
    image: '/portfolio/velocity.jpg',
    heroImage: '/portfolio/velocity-hero.jpg',
    logo: '/portfolio/logos/velocity-logo.png',
    colors: ['#FF6B35', '#F7931E', '#FFB81C'],
    description: 'Multi-channel marketing campaign for premium fitness brand including digital and print assets.',
    fullDescription: 'Velocity Fitness required an integrated marketing campaign to establish their brand as the premier fitness destination. We created cohesive digital and print materials that conveyed energy, strength, and transformation.',
    industry: 'Health & Wellness',
    services: ['Marketing Strategy', 'Graphic Design', 'Print Design', 'Digital Assets', 'Campaign Management'],
    timeline: '2 months',
    tools: ['Adobe Creative Suite', 'Illustrator', 'InDesign'],
    testimonial: {
      quote: 'This campaign has significantly increased our membership sign-ups. The creative work perfectly represents our brand.',
      author: 'James Patterson',
      role: 'Founder',
      company: 'Velocity Fitness',
    },
    galleryImages: ['/portfolio/velocity-gallery-1.jpg', '/portfolio/velocity-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/velocity-social-1.jpg', '/portfolio/velocity-social-2.jpg', '/portfolio/velocity-social-3.jpg'],
    printMockups: ['/portfolio/velocity-print-1.jpg', '/portfolio/velocity-print-2.jpg', '/portfolio/velocity-print-3.jpg'],
    uiMockups: ['/portfolio/velocity-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/velocity-before.jpg',
      after: '/portfolio/velocity-after.jpg',
    },
  },
  {
    id: '6',
    title: 'Serenity Wellness Spa',
    slug: 'serenity-spa',
    category: 'Branding',
    image: '/portfolio/serenity.jpg',
    heroImage: '/portfolio/serenity-hero.jpg',
    logo: '/portfolio/logos/serenity-logo.png',
    colors: ['#A569BD', '#9B59B6', '#E8DAEF'],
    description: 'Luxury spa brand identity with soothing color palette and elegant design system.',
    fullDescription: 'Serenity Spa required a complete brand identity that would evoke relaxation, luxury, and wellness. We developed a cohesive visual language with a soothing color palette and sophisticated design system.',
    industry: 'Wellness & Spa',
    services: ['Branding', 'Logo Design', 'Brand Guidelines', 'Website Design', 'Marketing Materials'],
    timeline: '3 months',
    tools: ['Adobe Creative Suite', 'Figma'],
    testimonial: {
      quote: 'Our brand is now perfectly aligned with the luxury spa experience we provide. Clients immediately sense the quality and care.',
      author: 'Elena Rodriguez',
      role: 'Owner',
      company: 'Serenity Wellness Spa',
    },
    galleryImages: ['/portfolio/serenity-gallery-1.jpg', '/portfolio/serenity-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/serenity-social-1.jpg', '/portfolio/serenity-social-2.jpg', '/portfolio/serenity-social-3.jpg'],
    printMockups: ['/portfolio/serenity-print-1.jpg', '/portfolio/serenity-print-2.jpg', '/portfolio/serenity-print-3.jpg'],
    uiMockups: ['/portfolio/serenity-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/serenity-before.jpg',
      after: '/portfolio/serenity-after.jpg',
    },
  },
  {
    id: '7',
    title: 'Luna Fashion Studio',
    slug: 'luna-fashion',
    category: 'Print',
    image: '/portfolio/luna.jpg',
    heroImage: '/portfolio/luna-hero.jpg',
    logo: '/portfolio/logos/luna-logo.png',
    colors: ['#1C1C1C', '#FFFFFF', '#FFD700'],
    description: 'High-end fashion brand collateral including lookbooks, catalogs, and promotional materials.',
    fullDescription: 'Luna Fashion Studio required sophisticated print materials that would position their brand as a premier luxury fashion house. We designed elegant lookbooks and catalogs that showcase their collections beautifully.',
    industry: 'Fashion',
    services: ['Print Design', 'Lookbook Design', 'Catalog Design', 'Photography Direction'],
    timeline: '4 months',
    tools: ['InDesign', 'Adobe Creative Suite', 'Photoshop'],
    testimonial: {
      quote: 'The print materials are absolutely stunning. They\'ve helped us attract high-end retailers and distributors.',
      author: 'Victoria Laurent',
      role: 'Creative Director',
      company: 'Luna Fashion Studio',
    },
    galleryImages: ['/portfolio/luna-gallery-1.jpg', '/portfolio/luna-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/luna-social-1.jpg', '/portfolio/luna-social-2.jpg', '/portfolio/luna-social-3.jpg'],
    printMockups: ['/portfolio/luna-print-1.jpg', '/portfolio/luna-print-2.jpg', '/portfolio/luna-print-3.jpg'],
    uiMockups: ['/portfolio/luna-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/luna-before.jpg',
      after: '/portfolio/luna-after.jpg',
    },
  },
  {
    id: '8',
    title: 'Horizon Real Estate',
    slug: 'horizon-realestate',
    category: 'Logo',
    image: '/portfolio/horizon.jpg',
    heroImage: '/portfolio/horizon-hero.jpg',
    logo: '/portfolio/logos/horizon-logo.png',
    colors: ['#0066CC', '#003D99', '#4D94FF'],
    description: 'Professional logo and brand guidelines for luxury real estate development company.',
    fullDescription: 'Horizon Real Estate needed a professional logo that conveyed trust, stability, and luxury in the real estate market. We created a sophisticated mark that works across all mediums and sizes.',
    industry: 'Real Estate',
    services: ['Logo Design', 'Brand Guidelines', 'Business Collateral', 'Marketing Materials'],
    timeline: '6 weeks',
    tools: ['Illustrator', 'Adobe Creative Suite'],
    testimonial: {
      quote: 'The new brand identity has elevated our company\'s perceived value in the luxury real estate market.',
      author: 'Robert Harrison',
      role: 'CEO',
      company: 'Horizon Real Estate',
    },
    galleryImages: ['/portfolio/horizon-gallery-1.jpg', '/portfolio/horizon-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/horizon-social-1.jpg', '/portfolio/horizon-social-2.jpg', '/portfolio/horizon-social-3.jpg'],
    printMockups: ['/portfolio/horizon-print-1.jpg', '/portfolio/horizon-print-2.jpg', '/portfolio/horizon-print-3.jpg'],
    uiMockups: ['/portfolio/horizon-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/horizon-before.jpg',
      after: '/portfolio/horizon-after.jpg',
    },
  },
  {
    id: '9',
    title: 'Gourmet Kitchen Appliances',
    slug: 'gourmet-appliances',
    category: 'Social Media',
    image: '/portfolio/gourmet.jpg',
    heroImage: '/portfolio/gourmet-hero.jpg',
    logo: '/portfolio/logos/gourmet-logo.png',
    colors: ['#2C3E50', '#E74C3C', '#ECF0F1'],
    description: 'Engaging social media strategy and content creation for premium kitchen appliance brand.',
    fullDescription: 'Gourmet Appliances needed a comprehensive social media strategy to showcase their premium kitchen products to home chefs and cooking enthusiasts. We created visually stunning content that inspired and engaged their audience.',
    industry: 'Home & Kitchen',
    services: ['Social Media Strategy', 'Content Creation', 'Photography', 'Video Production', 'Community Management'],
    timeline: '3 months',
    tools: ['Adobe Creative Suite', 'Premiere Pro'],
    testimonial: {
      quote: 'The social media content has driven significant traffic to our website and increased sales substantially.',
      author: 'Michael Chen',
      role: 'Marketing Manager',
      company: 'Gourmet Kitchen Appliances',
    },
    galleryImages: ['/portfolio/gourmet-gallery-1.jpg', '/portfolio/gourmet-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/gourmet-social-1.jpg', '/portfolio/gourmet-social-2.jpg', '/portfolio/gourmet-social-3.jpg'],
    printMockups: ['/portfolio/gourmet-print-1.jpg', '/portfolio/gourmet-print-2.jpg', '/portfolio/gourmet-print-3.jpg'],
    uiMockups: ['/portfolio/gourmet-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/gourmet-before.jpg',
      after: '/portfolio/gourmet-after.jpg',
    },
  },
  {
    id: '10',
    title: 'Aurora Digital Agency',
    slug: 'aurora-agency',
    category: 'UI/UX',
    image: '/portfolio/aurora.jpg',
    heroImage: '/portfolio/aurora-hero.jpg',
    logo: '/portfolio/logos/aurora-logo.png',
    colors: ['#667EEA', '#764BA2', '#F093FB'],
    description: 'Website redesign and interactive experience for digital marketing agency.',
    fullDescription: 'Aurora Digital Agency required a modern website redesign that would showcase their creative capabilities and attract premium clients. We created an interactive, visually stunning platform.',
    industry: 'Digital Services',
    services: ['Web Design', 'UI/UX Design', 'Interactive Design', 'Web Development', 'CMS Integration'],
    timeline: '3 months',
    tools: ['Figma', 'Adobe XD', 'Next.js', 'Tailwind CSS'],
    testimonial: {
      quote: 'Our new website has become our best sales tool. Client inquiries are up 200% since launch.',
      author: 'Alex Thompson',
      role: 'Founder',
      company: 'Aurora Digital Agency',
    },
    galleryImages: ['/portfolio/aurora-gallery-1.jpg', '/portfolio/aurora-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/aurora-social-1.jpg', '/portfolio/aurora-social-2.jpg', '/portfolio/aurora-social-3.jpg'],
    printMockups: ['/portfolio/aurora-print-1.jpg', '/portfolio/aurora-print-2.jpg', '/portfolio/aurora-print-3.jpg'],
    uiMockups: ['/portfolio/aurora-ui-1.jpg', '/portfolio/aurora-ui-2.jpg', '/portfolio/aurora-ui-3.jpg'],
    beforeAfter: {
      before: '/portfolio/aurora-before.jpg',
      after: '/portfolio/aurora-after.jpg',
    },
  },
  {
    id: '11',
    title: 'Vintage Collectibles',
    slug: 'vintage-collectibles',
    category: 'Print',
    image: '/portfolio/vintage.jpg',
    heroImage: '/portfolio/vintage-hero.jpg',
    logo: '/portfolio/logos/vintage-logo.png',
    colors: ['#8B7355', '#D2B48C', '#654321'],
    description: 'Premium catalogue design and print materials for luxury vintage collectibles marketplace.',
    fullDescription: 'Vintage Collectibles required high-end print materials that would position their brand as the premier destination for rare collectibles. We designed elegant catalogues and promotional materials.',
    industry: 'Retail & Collections',
    services: ['Catalogue Design', 'Print Design', 'Photography Direction', 'Branding'],
    timeline: '4 months',
    tools: ['InDesign', 'Adobe Creative Suite'],
    testimonial: {
      quote: 'The quality of the print materials reflects the quality of our products perfectly. Collectors are impressed.',
      author: 'Gregory Woods',
      role: 'Owner',
      company: 'Vintage Collectibles',
    },
    galleryImages: ['/portfolio/vintage-gallery-1.jpg', '/portfolio/vintage-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/vintage-social-1.jpg', '/portfolio/vintage-social-2.jpg', '/portfolio/vintage-social-3.jpg'],
    printMockups: ['/portfolio/vintage-print-1.jpg', '/portfolio/vintage-print-2.jpg', '/portfolio/vintage-print-3.jpg'],
    uiMockups: ['/portfolio/vintage-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/vintage-before.jpg',
      after: '/portfolio/vintage-after.jpg',
    },
  },
  {
    id: '12',
    title: 'NeoVision Tech',
    slug: 'neovision-tech',
    category: 'Branding',
    image: '/portfolio/neovision.jpg',
    heroImage: '/portfolio/neovision-hero.jpg',
    logo: '/portfolio/logos/neovision-logo.png',
    colors: ['#00D9FF', '#0099CC', '#003D66'],
    description: 'Modern tech startup branding including logo, website design, and brand guidelines.',
    fullDescription: 'NeoVision Tech needed a cutting-edge brand identity that would position them as an innovative tech startup. We created a modern visual language that conveys innovation and forward-thinking.',
    industry: 'Technology',
    services: ['Brand Strategy', 'Logo Design', 'Brand Guidelines', 'Web Design', 'Marketing Materials'],
    timeline: '3 months',
    tools: ['Adobe Creative Suite', 'Figma'],
    testimonial: {
      quote: 'The brand identity has helped us attract top talent and investment. It perfectly captures our vision.',
      author: 'Lisa Park',
      role: 'Co-Founder',
      company: 'NeoVision Tech',
    },
    galleryImages: ['/portfolio/neovision-gallery-1.jpg', '/portfolio/neovision-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/neovision-social-1.jpg', '/portfolio/neovision-social-2.jpg', '/portfolio/neovision-social-3.jpg'],
    printMockups: ['/portfolio/neovision-print-1.jpg', '/portfolio/neovision-print-2.jpg', '/portfolio/neovision-print-3.jpg'],
    uiMockups: ['/portfolio/neovision-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/neovision-before.jpg',
      after: '/portfolio/neovision-after.jpg',
    },
  },
  {
    id: '13',
    title: 'Botanical Botanicals',
    slug: 'botanical-products',
    category: 'Marketing',
    image: '/portfolio/botanical.jpg',
    heroImage: '/portfolio/botanical-hero.jpg',
    logo: '/portfolio/logos/botanical-logo.png',
    colors: ['#228B22', '#90EE90', '#ADFFAD'],
    description: 'Integrated marketing campaign for organic botanical products across digital and print channels.',
    fullDescription: 'Botanical Botanicals required an integrated marketing campaign to launch their new organic product line. We created cohesive digital and print assets that communicated their commitment to natural beauty.',
    industry: 'Beauty & Personal Care',
    services: ['Campaign Strategy', 'Graphic Design', 'Print Design', 'Digital Assets', 'Brand Guidelines'],
    timeline: '2 months',
    tools: ['Adobe Creative Suite', 'Illustrator'],
    testimonial: {
      quote: 'The marketing campaign successfully launched our organic line and exceeded sales projections by 150%.',
      author: 'Nina Patel',
      role: 'Founder',
      company: 'Botanical Botanicals',
    },
    galleryImages: ['/portfolio/botanical-gallery-1.jpg', '/portfolio/botanical-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/botanical-social-1.jpg', '/portfolio/botanical-social-2.jpg', '/portfolio/botanical-social-3.jpg'],
    printMockups: ['/portfolio/botanical-print-1.jpg', '/portfolio/botanical-print-2.jpg', '/portfolio/botanical-print-3.jpg'],
    uiMockups: ['/portfolio/botanical-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/botanical-before.jpg',
      after: '/portfolio/botanical-after.jpg',
    },
  },
  {
    id: '14',
    title: 'Zenith Coaching',
    slug: 'zenith-coaching',
    category: 'Logo',
    image: '/portfolio/zenith.jpg',
    heroImage: '/portfolio/zenith-hero.jpg',
    logo: '/portfolio/logos/zenith-logo.png',
    colors: ['#FFB700', '#CC9300', '#FFE680'],
    description: 'Professional coaching business branding with minimalist logo and complete visual identity.',
    fullDescription: 'Zenith Coaching required a professional brand identity that would establish credibility and attract high-value clients. We created a minimalist yet sophisticated visual identity.',
    industry: 'Coaching & Development',
    services: ['Logo Design', 'Brand Guidelines', 'Website Design', 'Business Collateral'],
    timeline: '6 weeks',
    tools: ['Adobe Creative Suite', 'Figma'],
    testimonial: {
      quote: 'The professional branding has elevated my coaching practice. I\'ve attracted many more premium clients.',
      author: 'Dr. Jonathan Wells',
      role: 'Founder',
      company: 'Zenith Coaching',
    },
    galleryImages: ['/portfolio/zenith-gallery-1.jpg', '/portfolio/zenith-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/zenith-social-1.jpg', '/portfolio/zenith-social-2.jpg', '/portfolio/zenith-social-3.jpg'],
    printMockups: ['/portfolio/zenith-print-1.jpg', '/portfolio/zenith-print-2.jpg', '/portfolio/zenith-print-3.jpg'],
    uiMockups: ['/portfolio/zenith-ui-1.jpg'],
    beforeAfter: {
      before: '/portfolio/zenith-before.jpg',
      after: '/portfolio/zenith-after.jpg',
    },
  },
  {
    id: '15',
    title: 'Chromatic Studios',
    slug: 'chromatic-studios',
    category: 'UI/UX',
    image: '/portfolio/chromatic.jpg',
    heroImage: '/portfolio/chromatic-hero.jpg',
    logo: '/portfolio/logos/chromatic-logo.png',
    colors: ['#E31B23', '#F9A825', '#1B1B1B'],
    description: 'Creative portfolio platform UI design with interactive galleries and user-centric features.',
    fullDescription: 'Chromatic Studios required a modern portfolio platform UI that would showcase creative work beautifully. We designed an interactive, user-centric interface with advanced gallery features.',
    industry: 'Creative Services',
    services: ['UI/UX Design', 'Web Design', 'Interactive Design', 'Prototyping'],
    timeline: '3 months',
    tools: ['Figma', 'Adobe XD', 'Framer'],
    testimonial: {
      quote: 'The portfolio platform is a game-changer for our creative team. Client feedback has been overwhelmingly positive.',
      author: 'Sophie Laurent',
      role: 'Creative Director',
      company: 'Chromatic Studios',
    },
    galleryImages: ['/portfolio/chromatic-gallery-1.jpg', '/portfolio/chromatic-gallery-2.jpg'],
    socialMediaMockups: ['/portfolio/chromatic-social-1.jpg', '/portfolio/chromatic-social-2.jpg', '/portfolio/chromatic-social-3.jpg'],
    printMockups: ['/portfolio/chromatic-print-1.jpg', '/portfolio/chromatic-print-2.jpg', '/portfolio/chromatic-print-3.jpg'],
    uiMockups: ['/portfolio/chromatic-ui-1.jpg', '/portfolio/chromatic-ui-2.jpg'],
    beforeAfter: {
      before: '/portfolio/chromatic-before.jpg',
      after: '/portfolio/chromatic-after.jpg',
    },
  },
]

export const categories = ['All Work', 'Branding', 'Social Media', 'Print', 'UI/UX', 'Logo', 'Marketing']
